[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
let g:neosnippet#enable_snipmate_campatibility = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete'
hook_add = '''
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neosnippet#snippets_directory = '~/.vim/snippets'
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'mileszs/ack.vim'
hook_add = '''
let g:ackprg = "ag"
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
marged = 0

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=250
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'junegunn/fzf'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
\ 'python': ['pylint']
\}
'''
