[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddu.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
  let g:tcomment_opleader1 = '<Space>g'
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'mileszs/ack.vim'
hook_add = '''
  let g:ackprg = "ag --silent"
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
marged = 0

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set updatetime=250
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'junegunn/fzf'

# [[plugins]]
# repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddc-ui-native'

# sources
[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-omni'

[[plugins]]
repo = 'shun/ddc-vim-lsp'

# filters
[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

# lsp
[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_source = '''
  let g:lsp_diagnostics_echo_cursor = 1
'''

