[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
hook_source = '''
  let g:neosnippet#snippets_directory = '~/.vim/rc/snippets'
  let g:neosnippet#enable_snipmate_campatibility = 1
  imap <C-i>     <Plug>(neosnippet_expand_or_jump)
  smap <C-i>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-i>     <Plug>(neosnippet_expand_target)
'''

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'majutsushi/tagbar'
on_if = ' "" !=# findfile(".tags", ".;") '
hook_source = '''
  nnoremap <silent>tt :TagbarToggle<CR>
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_event = 'CursorMoved'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_source = '''
"  if !exists('g:context_filetype#filetypes')
"    let g:context_filetype#filetypes = {}
"  endif
" g:context_filetype#filetypes.hoge =[{'filetype': , 'start': ,'end':}]
 let g:context_filetype#search_offset = 20
'''
