[[plugins]]
repo = 'majutsushi/tagbar'
on_if = ' "" !=# findfile(".tags", ".;") '
hook_source = '''
  nnoremap <silent>tt :TagbarToggle<CR>
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_event = 'CursorMoved'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_source = '''
  if !exists('g:context_filetype#filetypes')
    let g:context_filetype#filetypes = {}
  endif
  let g:context_filetype#filetypes.html =[{'filetype': 'smarty', 'start': '{' ,'end':'}'}]
  let g:context_filetype#search_offset = 20
'''
